# Generated by Django 4.2.29 on 2026-03-18 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('notification_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_moved', 'Task Moved'), ('task_comment', 'Task Comment'), ('issue_created', 'Issue Created'), ('sprint_started', 'Sprint Started'), ('sprint_completed', 'Sprint Completed'), ('mention', 'Mention')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
