# Generated by Django 4.2.29 on 2026-03-18 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_id', models.PositiveIntegerField(db_index=True)),
                ('corporate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notification_type', models.CharField(default='email', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('corporate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('source_ip', models.CharField(blank=True, max_length=45)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_transactionlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
